#!C:\Users\Ilia\Desktop\UNI III semester\Relational ML RIL\tabzilla\TabZilla\Tabzilaenv\Scripts\python.exe
"""Small script to execute the igraph command line interface"""
from igraph.app.shell import main
main()
